import type { Metadata } from "next"
import "./globals.css"
import { Plus_Jakarta_Sans } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import { ReduxProvider } from "@/redux/provider"
import { ReactQueryProvider } from "@/react-query/provider"
import { ThemeProvider } from "@/components/theme"
const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] })
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`antialiased ${jakarta.className}`}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        disableTransitionOnChange
                    >
                        <ReduxProvider>
                            <ReactQueryProvider>{children}</ReactQueryProvider>
                        </ReduxProvider>
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    )
}
